service: chatbot-lex

provider:
  name: aws
  runtime: python3.12
  memorySize: 128
  timeout: 10
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lex:RecognizeText
            - lex:RecognizeUtterance
          Resource: "*"

functions:
  hello:
    handler: handlers/health.hello
    events:
      - httpApi:
          path: /
          method: get

  lex:
    handler: handlers/lex.lex
    timeout: 30
    events:
      - httpApi:
          path: /
          method: post

  twilio:
    handler: handlers/twilio.twilio
    timeout: 15
    events:
      - httpApi:
          path: /twilio
          method: post


plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-dotenv-plugin

custom:
  pythonRequirements:
    fileName: requirements.txt
