service: chatbot-lex

provider:
  name: aws
  runtime: python3.12
  memorySize: 128
  timeout: 10
  apiGateway:
    usagePlan:
      quota:
        limit: 5000
        offset: 2
        period: MONTH
      throttle:
        burstLimit: 40
        rateLimit: 20
  tracing:
    apiGateway: true
    lambda: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
          Resource: "*"
        - Effect: Allow
          Action:
            - lex:RecognizeText
            - lex:RecognizeUtterance
          Resource: "*"
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource: "*"

functions:
  hello:
    handler: handlers/health.hello
    events:
      - httpApi:
          path: /
          method: get

  lex:
    handler: handlers/lex.lex
    timeout: 30
    events:
      - httpApi:
          path: /
          method: post

  twilio:
    handler: handlers/twilio.twilio
    timeout: 15
    events:
      - httpApi:
          path: /twilio
          method: post

  upload_url:
    handler: handlers/upload.get_upload_url
    events:
      - httpApi:
          path: /upload-url
          method: post

  web_proxy:
    handler: handlers/proxy.web_proxy
    events:
      - httpApi:
          path: /web-proxy
          method: post


plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-dotenv-plugin

custom:
  pythonRequirements:
    dockerizePip: true
    fileName: requirements.txt
